Description: >
  Ec2 instance deployed by CircleCI

Parameters:
  EnvironmentName:
    Description: An environment name
    Type: String
    Default: CircleCI-Test

Resources: 
  InstanceSecurityGroup:
    Type: 'AWS::EC2::SecurityGroup'
    Properties:
      GroupDescription: Enable incoming traffic
      VpcId:
        Fn::ImportValue: !Sub '${EnvironmentName}-VPCID'
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '3000'
          ToPort: '3000'
          CidrIp: 0.0.0.0/0

  Ec2Instance:
    Type: 'AWS::EC2::Instance'
    Properties:
      KeyName: udacity
      SecurityGroupIds: 
        - !Ref InstanceSecurityGroup #!GetAtt InstanceSecurityGroup.GroupId
      ImageId: 'ami-0a91cd140a1fc148a'